### ISSUE TITLE
Improve it more

### ISSUE THREAD

**Issue by zedsalim** [RezoualiRaouf/python-projects#2]
When i create a new file i need to add .txt or it won't be created.
Add scroll bar in the texteara.

**Comment by daaaaaaanyyyyy** [comment]
kayna

**Comment by RezoualiRaouf** [comment]
cry about it!!!
![cry-about-it-cry](https://github.com/RezoualiRaouf/python-projects/assets/127851417/0f5d7775-9267-43da-9d31-93e83b354004)
